In [ ]:
import numpy as np
input_matrix = np.random.uniform(-1,1,size = (5,4)) #n = 5, d_1 = 4

In [ ]:
input_matrix

array([[-0.23925502,  0.86362946,  0.87592563,  0.08695557],
       [ 0.09765875,  0.71540402,  0.1260168 ,  0.57719701],
       [-0.25740584,  0.66803728, -0.78580076,  0.76041724],
       [-0.75658513,  0.91307788, -0.66342792, -0.89293767],
       [-0.22912177, -0.26416824,  0.67772326,  0.21119739]])

In [ ]:
wQ = np.random.uniform(-1,1,size = (4,8)) #d_2 = 8
wK = np.random.uniform(-1,1,size = (4,8))
wV = np.random.uniform(-1,1,size = (4,8))

In [ ]:
wQ,wK,wV

(array([[-0.84239585,  0.35721569, -0.26985982,  0.99459794, -0.50791812,
         -0.05948814, -0.24288766,  0.31335055],
        [-0.5489748 , -0.55276062, -0.03802332, -0.21899916, -0.41968322,
          0.85897256,  0.70723454,  0.84208625],
        [-0.46875593, -0.25432983,  0.75473099, -0.32757292,  0.01388656,
          0.68855425, -0.32859872, -0.29633338],
        [-0.43804564, -0.66331057,  0.57565241,  0.59329387,  0.33084921,
         -0.63152218, -0.08283037,  0.98778146]]),
 array([[ 0.5816306 ,  0.94090143,  0.96754004, -0.92507363, -0.7193876 ,
          0.87434393,  0.76925872,  0.84306904],
        [-0.33389868, -0.94421937,  0.77438727,  0.92842568,  0.93200389,
         -0.2614997 , -0.78379796, -0.00892883],
        [ 0.55644308, -0.8946675 ,  0.11974121,  0.65471995, -0.77495613,
          0.60657402, -0.37412208,  0.5381094 ],
        [ 0.68232197, -0.79833971, -0.38287185,  0.48181639, -0.39412751,
         -0.14296849,  0.7471586 , -0.88202671]]),
 array([[-0.

In [ ]:
Q = np.matmul(input_matrix,wQ) #X.W_Q
K = np.matmul(input_matrix,wK) #X.W_K
V = np.matmul(input_matrix,wV) #X.W_V

In [ ]:
Q,K,V

(array([[-0.72124922, -0.84329856,  0.74287166, -0.66243599, -0.19999606,
          1.30427479,  0.37387007,  0.4786069 ],
        [-0.78691585, -0.77547263,  0.37381743,  0.24162607, -0.1571306 ,
          0.33095957,  0.39301993,  1.16583483],
        [-0.11464671, -0.76575432, -0.11126966,  0.30624301,  0.09104843,
         -0.43214852,  0.73020722,  1.4658718 ],
        [ 0.83822066, -0.01395307, -0.84527765, -1.26491474, -0.30356062,
          0.93642052,  1.12148933, -0.15361748],
        [-0.07216796, -0.2482788 ,  0.70495035, -0.26673309,  0.30652781,
          0.11999016, -0.37137061, -0.28646303]]),
 array([[ 0.11921167, -1.89365334,  0.50888641,  1.63852688,  0.2639476 ,
          0.08385181, -1.12369354,  0.18522698],
        [ 0.28188423, -1.1571535 ,  0.44258543,  0.93446661,  0.27135813,
         -0.10777307, -0.10149532, -0.36534701],
        [-0.29117588, -0.77700815, -0.11696598,  0.71024437,  1.11704768,
         -0.98511482,  0.14051975, -1.31653078],
        [-1.72

In [ ]:
QK = np.matmul(Q,K.T) #Q.K^T

In [ ]:
QK

array([[ 0.52866477,  0.07463704, -1.77795205, -1.5371286 ,  0.0591627 ],
       [ 1.72139562,  0.52262819, -1.02161681,  0.14745389,  0.31555138],
       [ 1.32035524,  0.55232194, -0.44093361, -0.27033842,  0.48085524],
       [-3.6666671 , -1.54469792, -1.93449771, -6.18443002,  0.49390735],
       [ 0.83845576,  0.54229915,  0.49118192,  1.42742707, -0.44108357]])

In [ ]:
normalise_QK = []
for i in range(5):
    temp = [np.exp(QK[i,j])/sum(np.exp(QK[i])) for j in range(5)]
    normalise_QK.append(temp)
normalise_QK = np.array(normalise_QK)

In [ ]:
normalise_QK

array([[0.40214035, 0.25538531, 0.04005223, 0.05095831, 0.25146381],
       [0.54995562, 0.16584774, 0.03540401, 0.11396551, 0.13482712],
       [0.44024578, 0.20424083, 0.07564447, 0.08971514, 0.19015379],
       [0.01262795, 0.10541253, 0.07138457, 0.00101832, 0.80955665],
       [0.2207222 , 0.16414469, 0.15596492, 0.3977709 , 0.06139728]])

In [ ]:
Attention = np.matmul(normalise_QK,V) #convex combination of values of all the words

In [ ]:
Attention

array([[ 0.10889414,  0.63514412, -0.54553243, -0.28382997, -0.12977866,
         0.24933936,  0.36545903,  0.36943337],
       [ 0.25462509,  0.81593084, -0.64312502, -0.23578805, -0.1148926 ,
         0.3724295 ,  0.38790877,  0.42915418],
       [ 0.19382359,  0.64948407, -0.64410265, -0.19440019, -0.11427357,
         0.3184414 ,  0.30742187,  0.43862357],
       [-0.04061076,  0.38521284, -0.07049606, -0.59932103, -0.32786254,
        -0.33713811,  0.3793853 ,  0.07453401],
       [ 0.61524686,  0.45765491, -1.01200352,  0.36972934, -0.02410043,
         0.54047611, -0.16082415,  0.71085139]])