In [1]:
import numpy as np

In [2]:
A = np.array([[2,1,1],[3,2,1],[2,1,2]])

In [3]:
A

array([[2, 1, 1],
       [3, 2, 1],
       [2, 1, 2]])

In [4]:
B = np.linalg.inv(A)
B

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [5]:
A @ B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])